[tool.poetry]
name = "discord-gpt-bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "discord_gpt_bot"}]

[tool.poetry.dependencies]
python = "^3.8.6"
"discord.py" = "^1"
discord-py-slash-command = "^3"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
